### ISSUE TITLE
Upgrade to use newest stable Koa and node.js.

### ISSUE THREAD

**Issue by nihiliad** [UMNLibraries/janus#9]

**Comment by mberkowski** [comment]
This will need to be addressed sooner rather than later, as new deployments can't succeed with the dependencies as defined today.

Presently, koa dependencies fail outright with syntax errors. package.json defines `"next"` for the koa deps, and however those resolve as of Oct 2018, the application is unable to start.  

Targeting the dependency as `"koa-router": "v7.4.0"` does allow janus to start up.
